### PR TITLE
Migrate to orb-tools v11. Add orb-tools config files

### PR DESCRIPTION
**Pull request by mathomp4**
This PR is to migrate circleci-tools to use orb-tools v11.0:

https://github.com/CircleCI-Public/orb-tools-orb

I followed this guide:

https://github.com/CircleCI-Public/orb-tools-orb/blob/master/MIGRATION.md

### CODE REVIEW

**Comment by KyleTryon** [comment]
I took a look into it and I think the error you are receiving appears to be accurate. From what I can tell, there is no namespace registered to GEOS-ESM

And Today I Learned, I just went to the orb registry to check it out and noticed that it does exist, but it is all lowercase, and this actually matters. I ran a query again as geos-esm and found you. Try again, but with all lowercase.

**Comment by mathomp4** [comment]
> I took a look into it and I think the error you are receiving appears to be accurate. From what I can tell, there is no namespace registered to GEOS-ESM
> 
> And Today I Learned, I just went to the orb registry to check it out and noticed that it does exist, but it is all lowercase, and this actually matters. I ran a query again as geos-esm and found you. Try again, but with all lowercase.

Well I feel a bit dumb. I imagine I used `GEOS-ESM` when running the migrate script because, well, that's my org, but I didn't realize that it looks like every orb in the registry has a lowercase org?

I've pushed and we shall see!

**Comment by mathomp4** [comment]
And I did screw up the `GITHUB_TOKEN` it seems, but there was a nice error message for that one...

**Comment by mathomp4** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=dev:f6259dbed59725b3ad9920c6b83f5ac5358e1e8d

**Comment by mathomp4** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=dev:14e3a28dc13461071d6eb7c78b0839fbe567c558

**Comment by mathomp4** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=dev:1e04d2ef70a595b610a36f04cca707b5dafcd44a

**Comment by KyleTryon** [comment]
@mathomp4 The last step before that if applicable is to implement any tests for your orb you may have. 
https://github.com/GEOS-ESM/circleci-tools/blob/1e04d2ef70a595b610a36f04cca707b5dafcd44a/.circleci/test-deploy.yml#L10
https://circleci.com/docs/testing-orbs#integration-testing

**Comment by KyleTryon** [comment]
I also have a video on the release process here but yes you are correct!
https://circleci.com/docs/creating-orbs#issue-a-new-release-with-the-orb-development-kit

**Comment by mathomp4** [comment]
> @mathomp4 The last step before that if applicable is to implement any tests for your orb you may have.
> 
> https://github.com/GEOS-ESM/circleci-tools/blob/1e04d2ef70a595b610a36f04cca707b5dafcd44a/.circleci/test-deploy.yml#L10
> 
> 
> https://circleci.com/docs/testing-orbs#integration-testing

Yeah...let's just say I've been a bad dev and haven't really done that yet. At the moment I think it's just doing a checkout. 

That said, I'm not really sure what kind of tests I can do. I mean, this orb is used to direct like 20 minute long CI tests. Still, I'll ponder it! 😄

**Comment by mathomp4** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=dev:f2486e64f96d8f7de7bb48bf08f6eced6aaf6f72

**Comment by mathomp4** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=dev:f2486e64f96d8f7de7bb48bf08f6eced6aaf6f72

**Comment by mathomp4** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/geos-esm/circleci-tools?version=1.10.0

**Pull request merged**
